Codegen framework output test
apollographql/apollo-ios-dev pull request #135
Opened 2023-11-14 18:28 UTC by BobaFetters

- Added a Codegen test configuration to test taking codegen output and generating it into an XCFramework
- Added a new docs page that details general usage of Apollo code as an XCFramework as well as starts compiling tips for things to be aware of collected from apollographql/apollo-ios#3271

2023-11-14 19:41 UTC, AnthonyMDev requested changes
We should probably add all the generated files with the `.graphql.swift` extension [to be marked as generated](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github). This will automatically collapse them on PRs, and exclude them from contribution statistics.

2023-11-14 19:41 UTC, AnthonyMDev commented on docs/source/development/using-xcframework.mdx
> +If you need to use Apoll iOS and the code generation output as an XCFramework, this page will give a high level overview of how to do so, as well as collect some tips on things you may encounter that
```suggestion
If you need to use Apollo iOS and the code generation output as an XCFramework, this page will give a high level overview of how to do so, as well as collect some tips on things you may encounter that have been reported by the community.
```

2023-11-14 19:41 UTC, AnthonyMDev commented on docs/source/config.json
> +        "Apollo as an XCFramework": "/development/using-xcframework"
```suggestion
        "Including Apollo as an XCFramework": "/development/using-xcframework"
```

2023-11-14 19:41 UTC, AnthonyMDev commented on docs/source/development/using-xcframework.mdx
> +In order to use Apollo iOS as an XCFramework, we provide a [apollo-ios-xcframework]() repository that can generate XCFrameworks from the Apollo iOS code including the necessary commands. This can be
Missing the link url to the framework project here.

2023-11-14 19:41 UTC, AnthonyMDev commented on docs/source/development/using-xcframework.mdx
> +You can also use the output from code generation as an XCFramework, you will need to configure this setup yourself, however you can use of [code generation test](https://github.com/apollographql/apol
```suggestion
You can also use the output from code generation as an XCFramework, you will need to configure this setup yourself. You can use the [code generation test](https://github.com/apollographql/apollo-ios-dev/tree/main/Tests/TestCodeGenConfigurations/CodegenXCFramework) project as an example/starting point for this.
```

2023-11-14 21:45 UTC, calvincestari commented
> We should probably add all the generated files with the .graphql.swift extension [to be marked as generated](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github). This will automatically collapse them on PRs, and exclude them from contribution statistics.

I had no idea about that! It's a very nice quality-of-life feature.

2023-11-16 19:10 UTC, BobaFetters commented
@AnthonyMDev Added the `.gitattributes` file, not sure if maybe those changes won't take affect for the files in this diff or because they are new? They don't appear to be auto-collapsed in the diff for me like it says they should be.

2023-11-17 18:56 UTC, calvincestari approved these changes
This looks good from my pov. If we can get that collapsed diff trick figured out it'd be great otherwise I'm good with this.

2023-11-17 18:57 UTC, calvincestari commented
I see that we've got some warnings showing up in the test codegen config project builds from merging in the defer work. They don't seem to be failing the CI test so I'm not going to act on them just yet. Merging in the rest of defer will clear those up.

2023-11-17 19:04 UTC, merged